zoom: "63.25%"
title: "Widad Zizouan - Resume"
firstName: "Widad"
lastName: "Zizouan"
position: "Recent Master's graduate in Software Engineering and Artificial Intelligence."
links:
  - url: "https://github.com/widadzizouan"
    icon: "fab fa-github"
  # - url: "https://www.instagram.com/riiswa"
  #   icon: "fab fa-instagram"
  - url: "https://www.linkedin.com/in/widadzizouan/"
    icon: "fab fa-linkedin"
  # - url: "https://warisradji.com"
  #   icon: "fas fa-globe"
details:
  - key: "Age"
    value: "23 years"
  - key: "Languages"
    value: "French, English, Arabic, Spanish"
  - key: "Location"
    value: "Paris"
  - key: "Phone"
    value: "+33 6 26 27 42 07"
  - key: "E-mail"
    value: "widad.zizouan16@gmail.com"
  # - key: "Website"
  #   value: "https://warisradji.com"
  - key: "Interests"
    value: "Philosophy, Litterature, AI, Gym, Dance"
description: "I am a Computer Science engineer deeply fascinated by the intersection of artificial intelligence and the human journey. Intrigued by our evolution from learning how to use primitive tools to crafting sophisticated AI models, I am passionately dedicated to contributing to this extraordinary trajectory of progress."
# description: "Dedicated to enhancing human intelligence through AI, Brain-Computer Interfaces, and Education. I am looking for an Internship in which I can learn from great minds and harness my skills in AI/RL, BCI, and Software Engineering to have a positive impact on the project."
# description: "Dedicated to enhancing human intelligence through AI, Brain Computer Interfaces and Education. I am looking for an internship enabling me to leverage my skills in AI/RL, BCI and Software Engineering in order to make a meaningfull contribution, and at the same time improve skills. " #"I am fascinated by the concept of Intelligence and looking for an opportunity to explore it through Artificial Intelligence, Reinforcement Learning and Brain Computer Interfacing."

jobs:
  - date: "Sept 2023 - Feb 2024"
    company: "Groupe Casino"
    logo: "img/logo/logoCasino.png"
    arrow: 50
    position: "Machine Learning Intern • Paris"
    description: "Led the end-to-end development and deployment of a sales forecast and inventory optimization project deployed in more than 100 retail stores. Employed TIDE (Time-series Dense Encoder), a state-of-the-art Google model, outperforming the existing model in production by an error reduction of 10% in the MAE value."
    badges:
      - name: "VertexAI"
        icon: "img/ico/vertexai.png"
      - name: "BigQuery"
        icon: "img/ico/logoBigquery.png"
      - name: "G Cloud"
        icon: "img/ico/google-cloud.png"
      - name: "SQL"
        icon: "img/ico/sql.png"
      - name: "Python"
        icon: "img/ico/python.png"
      - name: "PyTorch"
        icon: "img/ico/pytorch.png"
      - name: "Pandas"
        icon: "img/ico/pandas.png"
      - name: "matplotlib"
        icon: "img/ico/matplotlib.png"
      - name: "Looker Studio"
        icon: "img/ico/lookerstudio.svg"
      
    link: 
    id: casino
  - date: "Apr 2022 - Apr 2023"
    company: "Snow GMAO"
    logo: "img/logo/snow-gmao.png"
    arrow: 50
    position: "CO-FOUNDER (with Théo Michel) • Val d'Isère"
    description: "Co-founded a startup aimed at simplifying equipment maintenance for small companies using AI, overseeing a team of 9. Went through all the stages of creating a company, and successfully developed a leading-edge app."
    badges:
      - name: "Flutter"
        icon: "img/ico/flutter.png"
      - name: "Firebase"
        icon: "img/ico/firebase.png"
      - name: "G Cloud"
        icon: "img/ico/google-cloud.png"
      - name: "ML Kit"
        icon: "img/ico/ml-kit.png"
    link: https://snow-cannon-gmao-website.firebaseapp.com/
    id: snow
  - date: "Aug 2021 - January 2022 "
    company: "Le Connecteur"
    logo: "img/logo/connecteur.png"
    arrow: 50
    position: "LEAD DEVELOPER/ PRODUCT OWNER • Freelance • Biarritz"
    description: "Led a team of five to develop a service for managing coworking space reservations through a WooCommerce site and a Flutter application for QR code scanning. Service has been running smoothly for 2 years."
    badges:
      - name: "Flutter"
        icon: "img/ico/flutter.png"
      - name: "SQL"
        icon: "img/ico/sql.png"
      - name: "Firebase"
        icon: "img/ico/firebase.png"
      - name: "Big Querry"
        icon: "img/ico/big-query.png"
      - name: "Data Studio"
        icon: "img/ico/data-studio.png"
      - name: "G Cloud"
        icon: "img/ico/google-cloud.png"
    link: https://www.leconnecteur-biarritz.fr/
    id: connecteur
  - date: "May 2020 - July 2020"
educations:
  # - date: "Feb 2023 - July 2023"
  #   degree: "Exchange program"
  #   logo: "img/logo/KAIST.png"
  #   school: "Korean Advanced Institute of Science and Technology (KAIST), South Korea"
  #   description: "Participated in leading-edge projects at KAIST, widely regarded as the top engineering school in South Korea, known for its research-oriented focus."
  #   arrow: 50
  #   knowledges:
  #     - Deep Reinforcement Learning
  #     - Introduction to Autonomous Robotics
  #     - Graph Machine Learning
  #     - IOT Data Science
  #   link: https://www.kaist.ac.kr/en/html/kaist/01.html#0112

  - date: "Oct 2022 - August 2023"
    degree: "Exchange program"
    logo: "img/logo/TU_berlin.png"
    school: "Technical University Berlin, Germany"
    description: "Enrolled in courses on Machine Learning, taught by renowned experts like Klaus-Robert Müller, one of the pioneers in the field, I also delved into a highly theoretical exploration, drawing insights from key works that have significantly shaped the landscape."
    arrow: 50
    knowledges:
      - Machine Learning 1-X 
      - Python programming for Machine learning
      - Deep Learning 1 
      - Reinforcement Learning Research Project (LIS Lab)
      - Machine Learning 2-X
      - Mathematics of Machine Learning
      - Deep Learning 2 
      - Theory and Algorithms of Machine Learning 
    link: https://www.tu.berlin/en/

  - date: "2020 - 2023"
    degree: "Engineer's degree in Computer Science - Artificial Intelligence Major - PhD track "
    logo: "img/logo/enseirb.png"
    school: "ENSEIRB-MATMECA - Graduate School in Electronics, Computer Science, Telecommunications, Mathematics and Mechanics, Bordeaux"
    description: "Mastered the necessary theoretical and practical aspects of computer sciences. Joined the PhD track, which prepares engineering students for scientific research and its applications."
    arrow: 50
    knowledges:
      - Functional Programing
      - OOP
      - Compiler Theory
      - Probability and Statistics
      - Numerical Methods
      - System Programming
      - Computability Theory
      - Robotics
      - Machine Learning
      - Deep Learning 
      - Search Algorithms
      - Cryptology 
      - Network Architecture

    link: https://enseirb-matmeca.bordeaux-inp.fr/fr/informatique
  - date: "2018 - 2020"
    degree: "Preparatory Class for the Grandes Ecoles MPSI/MP"
    logo: "img/logo/logoCPGE.png"
    school: "CPGE Mohamed V Casablanca, Maroc"
    description: "Two year high-intensity study of advanced Mathematics, Physics and Philosophy to prepare for the entry into moroccan and french engineering schools. "
    arrow: 50
    knowledges:
      - Algebra
      - Linear Algebra
      - Differential Calculus
      - Analysis
      - Geometry
      - Topology
      - Numerical Analysis
      - Probability and Statistics
      - Thermodynamics
      - Classical Mechanics
      - Electromagnetism
      - Electricity
      - Statistical Mechanics
      - Fluid Mechanics
      - Waves
      - Quantum Physics
      - Philosophy
    awards: 
      - Top 3% candidates nationwide in the MP (Mathematics and Physics) track. 
      - Highest ranked woman in Casablanca.
      - Two scholarships reserved for the top 300 engineering students in Morocco.

  


projects:
  - date: "2023-2024"
    name: "Chatbot"
    position: "RESEARCHER"
    description: "Built a chatbot for Wellputt, a company that designs golf training equipment, for after-sales service. Fine-tuned BERT to achieve 91% for the F1 score metric. "
    badges:
    - name: "Python"
      icon: "img/ico/python.png"
    - name: "HuggingFace"
      icon: "img/ico/hugg.png"
    - name: "LangChain"
      icon: "img/ico/langchain3.png"
    id: chatbotWellputt
  - date: "2022-2023"
    name: "Smarter Subgoal Selection"
    position: "RESEARCHER"
    description: "Research on predicting subgoals in puzzles and connecting it to subgoals in RL. Implementation of the algorithm, training, and exploration of the task understanding."
    badges:
    - name: "Python" 
      icon: "img/ico/python.png"
    - name: "Pytorch"
      icon: "img/ico/pytorch.png"
    id: SSS
    # link: https://hal.science/hal-04175058
  - date: "2022"
    name: "Sim CLR Phd Track Project"
    position: "RESEARCHER"
    description: "Conducted research on the effectiveness of the contrastive self-supervised learning method Sim-CLR on various datasets, and explored its performance on resource-constrained hardware."
    badges:
    - name: "Python"
      icon: "img/ico/python.png"
    - name: "Pytorch"
      icon: "img/ico/pytorch.png"
    - name: "Weights and Biases"
      icon: "img/ico/wb.svg"
    id: sim_clr
    link: https://hal.science/hal-04175012

  - date: "2021"
    name: "Walking Hexapod"
    position: "DEVELOPER"
    description: " Developed and implemented an efficient inverse kinematics and walking pattern for a 6-legged robot, demonstrating best in class precise and stable locomotion."
    badges:
    - name: "Python"
      icon: "img/ico/python.png"
    - name: "PyBullet"
      icon: "img/ico/py-bullet.png"
    id: hexapod
    link: https://pitch.com/embed/46097a0e-ce72-4606-84ba-ea0834365475
  - date: "2022"
    name: "End of year Project in collaboration with Pollen Robotics"
    position: "Developper"
    description: "Fine-tuned Gpt model (2.5) of OpenAI to make the robot Reachy-Mini performs basic tasks: Conversations, Giving accurate Weather Informations, Identifying tasks like taking photos of groups or individual people and sending them to the given email adresses."
    badges:
    - name: "Python"
      icon: "img/ico/python.png"
    - name: "Pytorch"
      icon: "img/ico/pytorch.png"
    - name: "OpenCV"
      icon: "img/ico/open-cv.png"
    - name: "OpenAI"
      icon: "img/ico/openai.png"
    id: pollenRobotics
    link: https://hal.science/hal-04175012
skills:
  - icon: fas fa-robot
    category: Machine Learning
    content: Pytorch, TensorFlow, Scikit-learn, OpenCV, NLTK, Google Cloud
  - icon: fas fa-code
    category: Programming
    content: C, C++, Python, JavaScript, Java, Dart, SQL
  - icon: fas fa-database
    category: Data Science
    content: Firebase, BigQuery, Pandas, Plotly, Matplotlib, Looker Studio
  - icon: fas fa-globe
    category: Application Framework
    content: Flutter, Android, iOS, Web, React, Tailwind
  - icon: fas fa-robot
    category: Generative AI
    content:  LangChain, HuggingFace

  # - icon: fas fa-chart-pie
  #   category: Data Visualization
  #   content: 
  - icon: fas fa-balance-scale
    category: Soft Skills
    content: Adaptability, Problem-Solving, Curiosity, Rigorousness, Team Spirit


